apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/k4ahr/gitops-lab.git'
    path: overlays/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/k4ahr/gitops-lab.git'
    path: overlays/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true